# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\Administrator\boat\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 724)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 0))
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(62, 144,218);")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.head = QtWidgets.QWidget(self.centralWidget)
        self.head.setMinimumSize(QtCore.QSize(0, 50))
        self.head.setMaximumSize(QtCore.QSize(16777215, 100))
        self.head.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0454545 rgba(62, 144, 218, 255), stop:0.977273 rgba(141, 189, 233, 255));")
        self.head.setObjectName("head")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.head)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.head_layout = QtWidgets.QHBoxLayout()
        self.head_layout.setSpacing(0)
        self.head_layout.setObjectName("head_layout")
        self.logo = QtWidgets.QWidget(self.head)
        self.logo.setMinimumSize(QtCore.QSize(170, 20))
        self.logo.setMaximumSize(QtCore.QSize(170, 16777215))
        self.logo.setStyleSheet("\n"
"border-image: url(:/res/logo.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.logo.setObjectName("logo")
        self.head_layout.addWidget(self.logo)
        self.title = QtWidgets.QLabel(self.head)
        self.title.setMinimumSize(QtCore.QSize(0, 0))
        self.title.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.title.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.title.setLineWidth(1)
        self.title.setMidLineWidth(1)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setScaledContents(False)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setIndent(-1)
        self.title.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.title.setObjectName("title")
        self.head_layout.addWidget(self.title)
        self.select = QtWidgets.QLabel(self.head)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.select.setFont(font)
        self.select.setText("")
        self.select.setAlignment(QtCore.Qt.AlignCenter)
        self.select.setObjectName("select")
        self.head_layout.addWidget(self.select)
        self.green_pushButton = QtWidgets.QPushButton(self.head)
        self.green_pushButton.setEnabled(True)
        self.green_pushButton.setMinimumSize(QtCore.QSize(45, 45))
        self.green_pushButton.setMaximumSize(QtCore.QSize(45, 45))
        self.green_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.green_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/backsig.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.green_pushButton.setIcon(icon)
        self.green_pushButton.setIconSize(QtCore.QSize(35, 35))
        self.green_pushButton.setCheckable(True)
        self.green_pushButton.setFlat(True)
        self.green_pushButton.setObjectName("green_pushButton")
        self.head_layout.addWidget(self.green_pushButton)
        self.yellow_pushButton = QtWidgets.QPushButton(self.head)
        self.yellow_pushButton.setEnabled(True)
        self.yellow_pushButton.setMinimumSize(QtCore.QSize(45, 45))
        self.yellow_pushButton.setMaximumSize(QtCore.QSize(45, 45))
        self.yellow_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.yellow_pushButton.setText("")
        self.yellow_pushButton.setIcon(icon)
        self.yellow_pushButton.setIconSize(QtCore.QSize(35, 35))
        self.yellow_pushButton.setCheckable(True)
        self.yellow_pushButton.setChecked(False)
        self.yellow_pushButton.setFlat(True)
        self.yellow_pushButton.setObjectName("yellow_pushButton")
        self.head_layout.addWidget(self.yellow_pushButton)
        self.red_pushButton = QtWidgets.QPushButton(self.head)
        self.red_pushButton.setEnabled(True)
        self.red_pushButton.setMinimumSize(QtCore.QSize(45, 45))
        self.red_pushButton.setMaximumSize(QtCore.QSize(45, 45))
        self.red_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.red_pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.red_pushButton.setText("")
        self.red_pushButton.setIcon(icon)
        self.red_pushButton.setIconSize(QtCore.QSize(35, 35))
        self.red_pushButton.setCheckable(True)
        self.red_pushButton.setAutoDefault(False)
        self.red_pushButton.setDefault(False)
        self.red_pushButton.setFlat(True)
        self.red_pushButton.setObjectName("red_pushButton")
        self.head_layout.addWidget(self.red_pushButton)
        self.homeButton = QtWidgets.QPushButton(self.head)
        self.homeButton.setMinimumSize(QtCore.QSize(45, 45))
        self.homeButton.setMaximumSize(QtCore.QSize(45, 45))
        self.homeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton.setStyleSheet("")
        self.homeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon1)
        self.homeButton.setIconSize(QtCore.QSize(45, 45))
        self.homeButton.setFlat(True)
        self.homeButton.setObjectName("homeButton")
        self.head_layout.addWidget(self.homeButton)
        self.now = QtWidgets.QLabel(self.head)
        self.now.setMinimumSize(QtCore.QSize(150, 20))
        self.now.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.now.setFont(font)
        self.now.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.835, y1:0.335227, x2:1, y2:0, stop:0 rgba(211, 224, 230, 0), stop:1 rgba(255, 255, 255, 0));")
        self.now.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.now.setObjectName("now")
        self.head_layout.addWidget(self.now)
        self.horizontalLayout_13.addLayout(self.head_layout)
        self.verticalLayout.addWidget(self.head)
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setStyleSheet("background-color: rgb(222, 233, 251);")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 995, 634))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4.addWidget(self.widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menuBar.setStyleSheet("background-color: rgb(62, 144,218);")
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setStyleSheet("background-color: rgb(62, 144,218);")
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setStyleSheet("background-color: rgb(62, 144,218);")
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.actionWarn = QtWidgets.QAction(MainWindow)
        self.actionWarn.setObjectName("actionWarn")
        self.actionHistory = QtWidgets.QAction(MainWindow)
        self.actionHistory.setObjectName("actionHistory")
        self.actionLook = QtWidgets.QAction(MainWindow)
        self.actionLook.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionLook.setObjectName("actionLook")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionServer = QtWidgets.QAction(MainWindow)
        self.actionServer.setObjectName("actionServer")
        self.menu.addAction(self.actionWarn)
        self.menu.addAction(self.actionStart)
        self.menu.addAction(self.actionServer)
        self.menu_2.addAction(self.actionHistory)
        self.menu_2.addAction(self.actionLook)
        self.menu_3.addAction(self.actionHelp)
        self.menu_3.addAction(self.actionAbout)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "油液在线监测系统"))
        self.title.setText(_translate("MainWindow", "油液在线监测系统"))
        self.homeButton.setToolTip(_translate("MainWindow", "主页"))
        self.now.setText(_translate("MainWindow", "TextLabel"))
        self.menu.setTitle(_translate("MainWindow", "系统设置"))
        self.menu_2.setTitle(_translate("MainWindow", "查询"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.actionWarn.setText(_translate("MainWindow", "报警参数设置"))
        self.actionHistory.setText(_translate("MainWindow", "历史查询"))
        self.actionLook.setText(_translate("MainWindow", "故障查询"))
        self.actionStart.setText(_translate("MainWindow", "采集设置"))
        self.actionHelp.setText(_translate("MainWindow", "使用说明"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
        self.actionServer.setText(_translate("MainWindow", "服务器设置"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

