# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\Administrator\boat\ui\tcpset.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tcpset(object):
    def setupUi(self, tcpset):
        tcpset.setObjectName("tcpset")
        tcpset.resize(686, 644)
        tcpset.setStyleSheet("background-color: rgb(62, 144,218);")
        self.verticalLayout = QtWidgets.QVBoxLayout(tcpset)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(tcpset)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.groupBox_3)
        self.tableView.setStyleSheet("background-color: rgb(222, 233, 251);")
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(50)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.tableView)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setMaximumSize(QtCore.QSize(180, 16777215))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_dev = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_dev.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_dev.setObjectName("lineEdit_dev")
        self.gridLayout_3.addWidget(self.lineEdit_dev, 3, 1, 1, 1)
        self.lineEdit_port = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_port.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_port.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.gridLayout_3.addWidget(self.lineEdit_port, 1, 1, 1, 1)
        self.pushButton_up = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_up.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_up.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_up.setStyleSheet("border-image: url(:/res/button3.png);")
        self.pushButton_up.setObjectName("pushButton_up")
        self.gridLayout_3.addWidget(self.pushButton_up, 6, 0, 1, 1)
        self.lineEdit_num = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_num.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_num.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.gridLayout_3.addWidget(self.lineEdit_num, 2, 1, 1, 1)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_ip.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_ip.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.gridLayout_3.addWidget(self.lineEdit_ip, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.pushButton_del = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_del.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_del.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_del.setStyleSheet("border-image: url(:/res/button3.png);")
        self.pushButton_del.setObjectName("pushButton_del")
        self.gridLayout_3.addWidget(self.pushButton_del, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_add.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_add.setStyleSheet("border-image: url(:/res/button3.png);")
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout_3.addWidget(self.pushButton_add, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.pushButton_down = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_down.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_down.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_down.setStyleSheet("border-image: url(:/res/button3.png);")
        self.pushButton_down.setObjectName("pushButton_down")
        self.gridLayout_3.addWidget(self.pushButton_down, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 7, 0, 1, 2)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(tcpset)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.interval = QtWidgets.QLineEdit(self.groupBox)
        self.interval.setMaximumSize(QtCore.QSize(150, 16777215))
        self.interval.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.interval.setObjectName("interval")
        self.gridLayout.addWidget(self.interval, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 2, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 2, 2, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 1, 3, 2, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 3, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 6, 0, 1, 1)
        self.start = QtWidgets.QPushButton(self.groupBox)
        self.start.setMinimumSize(QtCore.QSize(0, 20))
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start.setStyleSheet("border-image: url(:/res/button3.png);")
        self.start.setObjectName("start")
        self.gridLayout.addWidget(self.start, 7, 0, 1, 1)
        self.stop = QtWidgets.QPushButton(self.groupBox)
        self.stop.setMinimumSize(QtCore.QSize(0, 20))
        self.stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop.setStyleSheet("border-image: url(:/res/button3.png);")
        self.stop.setObjectName("stop")
        self.gridLayout.addWidget(self.stop, 7, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(tcpset)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(160, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.user = QtWidgets.QLineEdit(self.groupBox_2)
        self.user.setMinimumSize(QtCore.QSize(150, 0))
        self.user.setMaximumSize(QtCore.QSize(150, 16777215))
        self.user.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.user.setObjectName("user")
        self.gridLayout_2.addWidget(self.user, 0, 2, 1, 1)
        self.modify = QtWidgets.QPushButton(self.groupBox_2)
        self.modify.setMinimumSize(QtCore.QSize(0, 20))
        self.modify.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.modify.setStyleSheet("border-image: url(:/res/button3.png);")
        self.modify.setObjectName("modify")
        self.gridLayout_2.addWidget(self.modify, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMinimumSize(QtCore.QSize(160, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.initialize = QtWidgets.QPushButton(self.groupBox_2)
        self.initialize.setMinimumSize(QtCore.QSize(0, 20))
        self.initialize.setMaximumSize(QtCore.QSize(150, 16777215))
        self.initialize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.initialize.setStyleSheet("border-image: url(:/res/button3.png);")
        self.initialize.setObjectName("initialize")
        self.gridLayout_2.addWidget(self.initialize, 2, 2, 1, 1)
        self.password = QtWidgets.QLineEdit(self.groupBox_2)
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout_2.addWidget(self.password, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(tcpset)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 1)
        self.add = QtWidgets.QPushButton(self.groupBox_5)
        self.add.setMinimumSize(QtCore.QSize(80, 20))
        self.add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add.setStyleSheet("border-image: url(:/res/button3.png);")
        self.add.setObjectName("add")
        self.gridLayout_4.addWidget(self.add, 0, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.groupBox_5)
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 2, 13, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 9, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_5.addWidget(self.lineEdit_6, 2, 3, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 2, 17, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 5, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_5.addWidget(self.lineEdit_7, 2, 7, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 1, 11, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 17, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_5.addWidget(self.lineEdit_4, 1, 15, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 1, 7, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 13, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_5.addWidget(self.lineEdit_5, 1, 19, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 1, 3, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 2, 9, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_5.addWidget(self.lineEdit_9, 2, 15, 1, 2)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_5.addWidget(self.lineEdit_8, 2, 11, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 5, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_5.addWidget(self.lineEdit_10, 2, 19, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 3, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 3, 5, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 3, 9, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_5.addWidget(self.lineEdit_15, 3, 19, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 3, 17, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 3, 13, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_5.addWidget(self.lineEdit_14, 3, 15, 1, 2)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_5.addWidget(self.lineEdit_13, 3, 11, 1, 2)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_5.addWidget(self.lineEdit_12, 3, 7, 1, 2)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_5.addWidget(self.lineEdit_11, 3, 3, 1, 2)
        self.gridLayout_4.addWidget(self.widget, 1, 0, 1, 4)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_4.addWidget(self.comboBox_5, 0, 1, 1, 1)
        self.modify_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.modify_2.setMinimumSize(QtCore.QSize(80, 20))
        self.modify_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.modify_2.setStyleSheet("border-image: url(:/res/button3.png);")
        self.modify_2.setObjectName("modify_2")
        self.gridLayout_4.addWidget(self.modify_2, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(tcpset)
        self.comboBox_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tcpset)

    def retranslateUi(self, tcpset):
        _translate = QtCore.QCoreApplication.translate
        tcpset.setWindowTitle(_translate("tcpset", "Dialog"))
        self.groupBox_3.setTitle(_translate("tcpset", "设备设置"))
        self.pushButton_up.setText(_translate("tcpset", "向上移动"))
        self.label_7.setText(_translate("tcpset", "设备名称："))
        self.pushButton_del.setText(_translate("tcpset", "删除"))
        self.label_6.setText(_translate("tcpset", "端口号："))
        self.pushButton_add.setText(_translate("tcpset", "添加"))
        self.label_4.setText(_translate("tcpset", "ip地址："))
        self.pushButton_down.setText(_translate("tcpset", "向下移动"))
        self.label_5.setText(_translate("tcpset", "机组号："))
        self.checkBox_2.setText(_translate("tcpset", "是否需要打开状态栏"))
        self.groupBox.setTitle(_translate("tcpset", "采集设置"))
        self.label.setText(_translate("tcpset", "  周    期(min)     ："))
        self.label_8.setText(_translate("tcpset", "油泵档位："))
        self.comboBox.setItemText(0, _translate("tcpset", "0"))
        self.comboBox.setItemText(1, _translate("tcpset", "1"))
        self.comboBox.setItemText(2, _translate("tcpset", "2"))
        self.comboBox.setItemText(3, _translate("tcpset", "3"))
        self.comboBox.setItemText(4, _translate("tcpset", "4"))
        self.comboBox.setItemText(5, _translate("tcpset", "5"))
        self.comboBox.setItemText(6, _translate("tcpset", "6"))
        self.comboBox.setItemText(7, _translate("tcpset", "7"))
        self.comboBox.setItemText(8, _translate("tcpset", "8"))
        self.comboBox.setItemText(9, _translate("tcpset", "9"))
        self.label_9.setText(_translate("tcpset", "  运转时间(second)  ："))
        self.comboBox_2.setItemText(0, _translate("tcpset", "0"))
        self.comboBox_2.setItemText(1, _translate("tcpset", "30"))
        self.comboBox_2.setItemText(2, _translate("tcpset", "60"))
        self.comboBox_2.setItemText(3, _translate("tcpset", "90"))
        self.comboBox_2.setItemText(4, _translate("tcpset", "120"))
        self.label_10.setText(_translate("tcpset", "亮    度："))
        self.comboBox_3.setItemText(0, _translate("tcpset", "1"))
        self.comboBox_3.setItemText(1, _translate("tcpset", "2"))
        self.comboBox_3.setItemText(2, _translate("tcpset", "3"))
        self.comboBox_3.setItemText(3, _translate("tcpset", "4"))
        self.comboBox_3.setItemText(4, _translate("tcpset", "5"))
        self.comboBox_3.setItemText(5, _translate("tcpset", "6"))
        self.comboBox_3.setItemText(6, _translate("tcpset", "7"))
        self.comboBox_3.setItemText(7, _translate("tcpset", "8"))
        self.comboBox_3.setItemText(8, _translate("tcpset", "9"))
        self.label_11.setText(_translate("tcpset", "  油品型号选择      ："))
        self.checkBox.setText(_translate("tcpset", "是否接受不正常图像"))
        self.start.setText(_translate("tcpset", "启动"))
        self.stop.setText(_translate("tcpset", "中止"))
        self.groupBox_2.setTitle(_translate("tcpset", "用户设置"))
        self.label_3.setText(_translate("tcpset", "  密      码    ："))
        self.modify.setText(_translate("tcpset", "修改"))
        self.label_2.setText(_translate("tcpset", "  用    户    名    ："))
        self.initialize.setText(_translate("tcpset", "初始化"))
        self.groupBox_5.setTitle(_translate("tcpset", "油品公式"))
        self.label_16.setText(_translate("tcpset", " 油  品  型  号  名  称："))
        self.add.setText(_translate("tcpset", "增加"))
        self.label_17.setText(_translate("tcpset", "在线传感器新油黏度公式："))
        self.label_22.setText(_translate("tcpset", "x^2 +"))
        self.label_20.setText(_translate("tcpset", "离线实验新油黏度公式  ："))
        self.label_13.setText(_translate("tcpset", "x^3+"))
        self.label_19.setText(_translate("tcpset", "x + "))
        self.label_12.setText(_translate("tcpset", "x^4+"))
        self.label_15.setText(_translate("tcpset", "x + "))
        self.label_14.setText(_translate("tcpset", "x^2 +"))
        self.label_18.setText(_translate("tcpset", "x^3+"))
        self.label_21.setText(_translate("tcpset", "x^4+"))
        self.label_24.setText(_translate("tcpset", "水   分   公   式     ："))
        self.label_25.setText(_translate("tcpset", "x^4+"))
        self.label_26.setText(_translate("tcpset", "x^3+"))
        self.label_23.setText(_translate("tcpset", "x + "))
        self.label_27.setText(_translate("tcpset", "x^2 +"))
        self.modify_2.setText(_translate("tcpset", "修改"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tcpset = QtWidgets.QDialog()
    ui = Ui_tcpset()
    ui.setupUi(tcpset)
    tcpset.show()
    sys.exit(app.exec_())

