# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\Administrator\boat\ui\warn.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_warn(object):
    def setupUi(self, warn):
        warn.setObjectName("warn")
        warn.resize(539, 369)
        warn.setStyleSheet("background-color: rgb(62, 144,218);")
        self.gridLayout_2 = QtWidgets.QGridLayout(warn)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(warn)
        self.groupBox_3.setMinimumSize(QtCore.QSize(255, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 4, 0, 1, 1)
        self.lineEdit_water = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_water.setMaximumSize(QtCore.QSize(106, 16777215))
        self.lineEdit_water.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_water.setText("")
        self.lineEdit_water.setObjectName("lineEdit_water")
        self.gridLayout_3.addWidget(self.lineEdit_water, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_watermax = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_watermax.setMaximumSize(QtCore.QSize(106, 16777215))
        self.lineEdit_watermax.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_watermax.setText("")
        self.lineEdit_watermax.setObjectName("lineEdit_watermax")
        self.gridLayout_3.addWidget(self.lineEdit_watermax, 0, 1, 1, 1)
        self.lineEdit_watermin = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_watermin.setMaximumSize(QtCore.QSize(106, 16777215))
        self.lineEdit_watermin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_watermin.setText("")
        self.lineEdit_watermin.setObjectName("lineEdit_watermin")
        self.gridLayout_3.addWidget(self.lineEdit_watermin, 4, 1, 1, 1)
        self.lineEdit_water_s = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_water_s.setMaximumSize(QtCore.QSize(106, 16777215))
        self.lineEdit_water_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_water_s.setText("")
        self.lineEdit_water_s.setObjectName("lineEdit_water_s")
        self.gridLayout_3.addWidget(self.lineEdit_water_s, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(warn)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.lineEdit_vis_down = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_vis_down.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_vis_down.setText("")
        self.lineEdit_vis_down.setObjectName("lineEdit_vis_down")
        self.gridLayout.addWidget(self.lineEdit_vis_down, 1, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.lineEdit_vis_up = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_vis_up.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_vis_up.setText("")
        self.lineEdit_vis_up.setObjectName("lineEdit_vis_up")
        self.gridLayout.addWidget(self.lineEdit_vis_up, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 4, 1, 1)
        self.lineEdit_vis_sdown = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_vis_sdown.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_vis_sdown.setText("")
        self.lineEdit_vis_sdown.setObjectName("lineEdit_vis_sdown")
        self.gridLayout.addWidget(self.lineEdit_vis_sdown, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.lineEdit_vis_sup = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_vis_sup.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_vis_sup.setText("")
        self.lineEdit_vis_sup.setPlaceholderText("")
        self.lineEdit_vis_sup.setObjectName("lineEdit_vis_sup")
        self.gridLayout.addWidget(self.lineEdit_vis_sup, 0, 3, 1, 1)
        self.lineEdit_vismax = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_vismax.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_vismax.setText("")
        self.lineEdit_vismax.setObjectName("lineEdit_vismax")
        self.gridLayout.addWidget(self.lineEdit_vismax, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 0, 1, 1)
        self.lineEdit_vismin = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_vismin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_vismin.setText("")
        self.lineEdit_vismin.setObjectName("lineEdit_vismin")
        self.gridLayout.addWidget(self.lineEdit_vismin, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(warn)
        self.groupBox_4.setMinimumSize(QtCore.QSize(255, 0))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 6, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 4, 0, 1, 1)
        self.lineEdit_Num_grade = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_Num_grade.setMaximumSize(QtCore.QSize(106, 16777215))
        self.lineEdit_Num_grade.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Num_grade.setText("")
        self.lineEdit_Num_grade.setObjectName("lineEdit_Num_grade")
        self.gridLayout_4.addWidget(self.lineEdit_Num_grade, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEdit_Num_grade_s = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_Num_grade_s.setMaximumSize(QtCore.QSize(106, 16777215))
        self.lineEdit_Num_grade_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Num_grade_s.setText("")
        self.lineEdit_Num_grade_s.setObjectName("lineEdit_Num_grade_s")
        self.gridLayout_4.addWidget(self.lineEdit_Num_grade_s, 1, 1, 1, 1)
        self.lineEdit_Num_grade_min = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_Num_grade_min.setMaximumSize(QtCore.QSize(106, 16777215))
        self.lineEdit_Num_grade_min.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Num_grade_min.setText("")
        self.lineEdit_Num_grade_min.setObjectName("lineEdit_Num_grade_min")
        self.gridLayout_4.addWidget(self.lineEdit_Num_grade_min, 6, 1, 1, 1)
        self.lineEdit_Num_grade_max = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_Num_grade_max.setMaximumSize(QtCore.QSize(106, 16777215))
        self.lineEdit_Num_grade_max.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Num_grade_max.setText("")
        self.lineEdit_Num_grade_max.setObjectName("lineEdit_Num_grade_max")
        self.gridLayout_4.addWidget(self.lineEdit_Num_grade_max, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(warn)
        self.buttonBox.setMinimumSize(QtCore.QSize(280, 20))
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 2)

        self.retranslateUi(warn)
        self.buttonBox.accepted.connect(warn.accept)
        self.buttonBox.rejected.connect(warn.reject)
        QtCore.QMetaObject.connectSlotsByName(warn)

    def retranslateUi(self, warn):
        _translate = QtCore.QCoreApplication.translate
        warn.setWindowTitle(_translate("warn", "Dialog"))
        self.groupBox_3.setTitle(_translate("warn", "水分 (ppm)"))
        self.label_11.setText(_translate("warn", "黄色报警上限:"))
        self.label_12.setText(_translate("warn", "最   小   值:"))
        self.label_10.setText(_translate("warn", "最   大   值:"))
        self.label_9.setText(_translate("warn", "红色报警上限:"))
        self.groupBox.setTitle(_translate("warn", "黏度变化率(%)"))
        self.label.setText(_translate("warn", "红色报警上限:"))
        self.label_3.setText(_translate("warn", "红色报警下限:"))
        self.label_4.setText(_translate("warn", "黄色报警下限:"))
        self.label_17.setText(_translate("warn", "最大值:"))
        self.label_2.setText(_translate("warn", "黄色报警上限:"))
        self.label_18.setText(_translate("warn", "最小值:"))
        self.groupBox_4.setTitle(_translate("warn", "磨损烈度等级"))
        self.label_16.setText(_translate("warn", "最   小   值:"))
        self.label_14.setText(_translate("warn", "最   大   值:"))
        self.label_15.setText(_translate("warn", "黄色报警上限:"))
        self.label_13.setText(_translate("warn", "红色报警上限:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    warn = QtWidgets.QDialog()
    ui = Ui_warn()
    ui.setupUi(warn)
    warn.show()
    sys.exit(app.exec_())

