# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\Administrator\boat\ui\warntable.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_warntable(object):
    def setupUi(self, warntable):
        warntable.setObjectName("warntable")
        warntable.resize(827, 544)
        warntable.setStyleSheet("background-color: rgb(62, 144,218);")
        self.verticalLayout = QtWidgets.QVBoxLayout(warntable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(warntable)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 224, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0454545, QtGui.QColor(62, 144, 218))
        gradient.setColorAt(0.977273, QtGui.QColor(141, 189, 233))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0454545, QtGui.QColor(62, 144, 218))
        gradient.setColorAt(0.977273, QtGui.QColor(141, 189, 233))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0454545, QtGui.QColor(62, 144, 218))
        gradient.setColorAt(0.977273, QtGui.QColor(141, 189, 233))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 224, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0454545, QtGui.QColor(62, 144, 218))
        gradient.setColorAt(0.977273, QtGui.QColor(141, 189, 233))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0454545, QtGui.QColor(62, 144, 218))
        gradient.setColorAt(0.977273, QtGui.QColor(141, 189, 233))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0454545, QtGui.QColor(62, 144, 218))
        gradient.setColorAt(0.977273, QtGui.QColor(141, 189, 233))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0454545, QtGui.QColor(62, 144, 218))
        gradient.setColorAt(0.977273, QtGui.QColor(141, 189, 233))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0454545, QtGui.QColor(62, 144, 218))
        gradient.setColorAt(0.977273, QtGui.QColor(141, 189, 233))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0454545, QtGui.QColor(62, 144, 218))
        gradient.setColorAt(0.977273, QtGui.QColor(141, 189, 233))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0454545 rgba(62, 144, 218, 255), stop:0.977273 rgba(141, 189, 233, 255));")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(warntable)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 224, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 224, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.startdateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.startdateTimeEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.startdateTimeEdit.setDate(QtCore.QDate(2017, 1, 1))
        self.startdateTimeEdit.setObjectName("startdateTimeEdit")
        self.horizontalLayout.addWidget(self.startdateTimeEdit)
        self.label_3 = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 224, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 224, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(62, 144, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.enddateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.enddateTimeEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enddateTimeEdit.setDate(QtCore.QDate(2017, 1, 1))
        self.enddateTimeEdit.setObjectName("enddateTimeEdit")
        self.horizontalLayout.addWidget(self.enddateTimeEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-image: url(:/res/button3.png);")
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(warntable)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView = QtWidgets.QTableView(self.widget_2)
        self.tableView.setStyleSheet("background-color: rgb(222, 233, 251);")
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_2.addWidget(self.tableView)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.vis_changerate_sa_label = QtWidgets.QLabel(self.groupBox)
        self.vis_changerate_sa_label.setObjectName("vis_changerate_sa_label")
        self.verticalLayout_4.addWidget(self.vis_changerate_sa_label)
        self.vis_changerate_si_label = QtWidgets.QLabel(self.groupBox)
        self.vis_changerate_si_label.setObjectName("vis_changerate_si_label")
        self.verticalLayout_4.addWidget(self.vis_changerate_si_label)
        self.vis_changerate_a_label = QtWidgets.QLabel(self.groupBox)
        self.vis_changerate_a_label.setObjectName("vis_changerate_a_label")
        self.verticalLayout_4.addWidget(self.vis_changerate_a_label)
        self.vis_changerate_i_label = QtWidgets.QLabel(self.groupBox)
        self.vis_changerate_i_label.setObjectName("vis_changerate_i_label")
        self.verticalLayout_4.addWidget(self.vis_changerate_i_label)
        self.vis_changerate_max_label = QtWidgets.QLabel(self.groupBox)
        self.vis_changerate_max_label.setObjectName("vis_changerate_max_label")
        self.verticalLayout_4.addWidget(self.vis_changerate_max_label)
        self.vis_changerate_min_label = QtWidgets.QLabel(self.groupBox)
        self.vis_changerate_min_label.setObjectName("vis_changerate_min_label")
        self.verticalLayout_4.addWidget(self.vis_changerate_min_label)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.water_s_label = QtWidgets.QLabel(self.groupBox_3)
        self.water_s_label.setObjectName("water_s_label")
        self.verticalLayout_5.addWidget(self.water_s_label)
        self.water_label = QtWidgets.QLabel(self.groupBox_3)
        self.water_label.setObjectName("water_label")
        self.verticalLayout_5.addWidget(self.water_label)
        self.water_max_label = QtWidgets.QLabel(self.groupBox_3)
        self.water_max_label.setObjectName("water_max_label")
        self.verticalLayout_5.addWidget(self.water_max_label)
        self.water_min_label = QtWidgets.QLabel(self.groupBox_3)
        self.water_min_label.setObjectName("water_min_label")
        self.verticalLayout_5.addWidget(self.water_min_label)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Num_grade_s_label = QtWidgets.QLabel(self.groupBox_2)
        self.Num_grade_s_label.setObjectName("Num_grade_s_label")
        self.verticalLayout_3.addWidget(self.Num_grade_s_label)
        self.Num_grade_label = QtWidgets.QLabel(self.groupBox_2)
        self.Num_grade_label.setObjectName("Num_grade_label")
        self.verticalLayout_3.addWidget(self.Num_grade_label)
        self.Num_grade_max_label = QtWidgets.QLabel(self.groupBox_2)
        self.Num_grade_max_label.setObjectName("Num_grade_max_label")
        self.verticalLayout_3.addWidget(self.Num_grade_max_label)
        self.Num_grade_min_label = QtWidgets.QLabel(self.groupBox_2)
        self.Num_grade_min_label.setObjectName("Num_grade_min_label")
        self.verticalLayout_3.addWidget(self.Num_grade_min_label)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(warntable)
        QtCore.QMetaObject.connectSlotsByName(warntable)

    def retranslateUi(self, warntable):
        _translate = QtCore.QCoreApplication.translate
        warntable.setWindowTitle(_translate("warntable", "Dialog"))
        self.label.setText(_translate("warntable", "故 障 查 询 表"))
        self.label_2.setText(_translate("warntable", "起始时间："))
        self.startdateTimeEdit.setDisplayFormat(_translate("warntable", "yyyy-MM-dd HH:mm:ss"))
        self.label_3.setText(_translate("warntable", "结束时间："))
        self.enddateTimeEdit.setDisplayFormat(_translate("warntable", "yyyy-MM-dd HH:mm:ss"))
        self.pushButton.setText(_translate("warntable", "查询"))
        self.groupBox.setTitle(_translate("warntable", "黏度变化率(%)"))
        self.vis_changerate_sa_label.setText(_translate("warntable", "红色报警上限:"))
        self.vis_changerate_si_label.setText(_translate("warntable", "红色报警下限:"))
        self.vis_changerate_a_label.setText(_translate("warntable", "黄色报警上限:"))
        self.vis_changerate_i_label.setText(_translate("warntable", "黄色报警下限:"))
        self.vis_changerate_max_label.setText(_translate("warntable", "最   大   值:"))
        self.vis_changerate_min_label.setText(_translate("warntable", "最   小   值:"))
        self.groupBox_3.setTitle(_translate("warntable", "水分(ppm)"))
        self.water_s_label.setText(_translate("warntable", "红色报警上限:"))
        self.water_label.setText(_translate("warntable", "黄色报警上限:"))
        self.water_max_label.setText(_translate("warntable", "最   大   值:"))
        self.water_min_label.setText(_translate("warntable", "最   小   值:"))
        self.groupBox_2.setTitle(_translate("warntable", "磨损烈度等级"))
        self.Num_grade_s_label.setText(_translate("warntable", "红色报警上限:"))
        self.Num_grade_label.setText(_translate("warntable", "黄色报警上限:"))
        self.Num_grade_max_label.setText(_translate("warntable", "最   大   值:"))
        self.Num_grade_min_label.setText(_translate("warntable", "最   小   值:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    warntable = QtWidgets.QDialog()
    ui = Ui_warntable()
    ui.setupUi(warntable)
    warntable.show()
    sys.exit(app.exec_())

